2020-11-06 16:04:13,550 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2020-11-06 16:04:13,550 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\zhelt\AppData\Local\Programs\Python\Python39\lib\site-packages\instabot\bot\bot.py
2020-11-06 16:04:13,550 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2020-11-06 16:04:13,849 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2020-11-06 16:04:14,150 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2020-11-06 16:04:14,465 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2020-11-06 16:04:14,814 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2020-11-06 16:04:17,924 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2020-11-06 16:04:17,925 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/8631667338/Ced2IGNKvO/", "api_path": "/challenge/8631667338/Ced2IGNKvO/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true, "flow_render_type": 0}, "status": "fail", "error_type": "checkpoint_challenge_required"}'
2020-11-06 16:04:17,925 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2020-11-06 16:04:17,926 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2020-11-06 16:04:17,947 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
